services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: sportbook-app

    ports:
      - "8080:8080"

    environment:
      DB_DRIVER: ${DB_DRIVER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
  
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0

    container_name: sportbook-db

    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - sportbook_mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "sportbook",
          "-p${DB_PASSWORD}"        ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  sportbook_mysql_data: